site_name: 蓝牙 LED 矩阵控制器文档
theme:
  name: 'material'
  feature:
    tabs: true
  palette:
    primary: 'dark blue'
    accent: 'blue'
  static_templates:
    - 404.html

docs_dir: docs


nav:
  - 概述: index.md
  - 硬件:
    - 主板: hw/board.md
    - 设计: hw/design.md
    - 外壳: hw/casing.md
  - 固件:
    - 构建说明: fw/how_to_build.md
  - 通讯协议:
    - 蓝牙 BLE 协议: protocol/ble_protocol.md
    - 应用层报文协议: protocol/packages.md

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - pymdownx.superfences
  - toc:
      permalink: true
